services:
  # Oracle Database Lite
  db:
    image: container-registry.oracle.com/database/free:latest
    container_name: oracle-db
    ports:
      - "1522:1521"
    environment:
      - ORACLE_PWD=mochaloca
      - ORACLE_CHARACTERSET=AL32UTF8
      - ENABLE_ARCHIVELOG=true
      - ENABLE_FORCE_LOGGING=true
    volumes:
      - ./oracle-db:/opt/oracle/oradata

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-container
    restart: always
    volumes:
      - ./backend/src:/app/src
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - PORT=3000
      - USER_DB="C##PROYECTODB" # Usuario de la BD existente
      - PASSWORD_DB="mochaloca"
      - CONNECT_STRING="localhost:1521/FREE" # Nombre del contenedor + servicio
    command: npm run start:dev

volumes:
  oracle-db:
    external: true
